version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - redis
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgresql:5432/mydatabase

  postgresql:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

volumes:
  postgres_data: