version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - redis
    networks:
      - internal
      - shared-network

  postgresql:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal

networks:
  internal:
  shared-network:
    external: true

volumes:
  postgres_data:
  redis_data: