version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - redis
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres/mydatabase

  postgresql:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"