# Generated by Django 4.2 on 2024-08-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortURL', '0002_rename_orign_url_url_origin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, '匿名用戶'), (1, '一般使用者'), (2, '管理員')], default=1),
        ),
    ]
