# Generated by Django 4.2 on 2024-07-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oriUrl', models.CharField(max_length=200)),
                ('srtUrl', models.CharField(max_length=200)),
                ('creDate', models.DateTimeField(verbose_name='創建日期')),
            ],
        ),
    ]
