# Generated by Django 4.2 on 2024-08-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortURL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='orign_url',
            new_name='origin_url',
        ),
    ]
