# Generated by Django 4.2 on 2024-07-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortURL', '0002_alter_url_credate_alter_url_oriurl_alter_url_srturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='srtStr',
            field=models.CharField(default='NULL', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='srtUrl',
            field=models.URLField(),
        ),
    ]
