# Generated by Django 4.2 on 2024-07-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortURL', '0004_rename_credate_url_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
