# Generated by Django 4.2 on 2024-07-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortURL', '0005_url_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
